website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import current_user
from .models import Note, Links, Image, User
from sqlalchemy import func
from . import db
import json
from .security import CheckForSpecialSigns, DivideLinks, CheckIfNotTooBig
import os
from werkzeug.utils import secure_filename
from datetime import datetime
import uuid
from .security import SendEmail

# Uploading images
BASE_DIR = os.path.abspath(os.path.dirname(__file__))
UPLOAD_FOLDER_2 = os.path.join(BASE_DIR, 'static', 'uploads')
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}
MAX_IMAGES_SIZE = 25 * 1024 * 1024 #25MB

if not os.path.exists(UPLOAD_FOLDER_2):
    os.makedirs(UPLOAD_FOLDER_2)

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template("home.html", user=current_user)


@views.route('/cloud')
def shop():
    category = request.args.get('category', 'all')

    if category == 'all':
        filtered_notes = Note.query.all()
    else:
        filtered_notes = Note.query.filter_by(category=category).all()

    return render_template("shop.html", user=current_user, notes=filtered_notes, selected_category=category)

@views.route('/create', methods=['GET', 'POST'])
def facts():
    if request.method == 'POST':
        title = request.form.get('title')
        note = request.form.get('note')
        category = request.form.get('select')
        spec = request.form.get('spec')
        link = request.form.get('social')
        link = DivideLinks(link)
        files = request.files.getlist('images')

        print(f"FILES RECEIVED: {[file.filename for file in files]}")
        print(f"UPLOAD_FOLDER_2 = {UPLOAD_FOLDER_2}")

        if current_user.status == "blocked":
            flash('Your account is blocked. Contact us', category='error')
        elif len(note) >= 30000:
            flash('Description is too long', category='error')
        elif len(note) < 1:
            flash('Description is too short', category='error')
        elif len(title) < 1:
            flash('Title is too short', category='error')
        elif len(title) > 50:
            flash('Title is too long', category='error')
        elif CheckForSpecialSigns(title) == 1:
            flash('Do not use special characters', category='error')
        elif len(spec) > 500:
            flash('Specyfication is too long', category='error')  
        elif len(files) > 5:
            flash("You can upload up to 5 images", category='error')
        elif CheckIfNotTooBig(files, MAX_IMAGES_SIZE):
            flash("Your files are too big", category='error')
        else:
            new_note = Note(
                title=title,
                data=note,
                category=category,
                spec=spec,
                user_id=current_user.id,
                username=current_user.first_name
            )
            db.session.add(new_note)
            db.session.commit()

            for x in link:
                new_link = Links(link=x, note_id=new_note.id)
                db.session.add(new_link)

            for file in files:
                if file and allowed_file(file.filename) and file.mimetype.startswith('image/'):
                    filename = secure_filename(f"{uuid.uuid4().hex}_{file.filename}")
                    filepath = os.path.join(UPLOAD_FOLDER_2, filename)

                    try:
                        file.save(filepath)
                        print(f"SAVED FILE TO: {filepath}")
                        new_image = Image(path=filename, note_id=new_note.id)
                        db.session.add(new_image)
                    except Exception as e:
                        print(f"Error saving file {filename}: {e}")
                        flash('Something went wrong while saving an image.', category='error')

            db.session.commit()
            flash('Project created!', category='success')

    return render_template("facts.html", user=current_user)

@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)

    if note:
        images = Image.query.filter_by(note_id=noteId).all()
        for image in images:
            try:
                full_path = os.path.join(UPLOAD_FOLDER_2, image.path)
                print(f"Trying to delete: {full_path}")
                os.remove(full_path)
            except FileNotFoundError:
                pass
            db.session.delete(image)

        db.session.delete(note)
        db.session.commit()
            
    return jsonify({})

@views.route('/settings', methods=['GET', 'POST'])
def settings():
    if request.method == 'POST':
        action = request.form.get("action")
        problem = request.form.get("problem")

        if action == "back":
            return redirect(url_for('views.facts'))
        elif problem == "":
            flash("Your message is empty", category="success")
        elif action == "send_email" and current_user.status != "blocked":
            email = current_user.email
            SendEmail("nessdy.com@gmail.com", problem, 3, email)
            return redirect(url_for('views.settings'))
        else:
            flash("Your account is blocked", category="success")
        
    return render_template("settings.html", user=current_user, now=datetime.now())

@views.route('/admin', methods=['GET', 'POST'])
def admin():
    if request.method == 'POST':
        user_id_block = request.form.get('block')
        user_id_unblock = request.form.get('unblock')
        user_verify =  request.form.get("verify")
        user_delete = request.form.get("delete")

        if user_id_block:
            try:
                user_id = int(user_id_block)
                user = User.query.get(user_id)
                if user and user_id != 1: #It must be different than 1 because 1 is me (admin)
                    user.status = "blocked"
                    db.session.commit()
                else:
                    flash("User not found or is an admin", category="error")
            except ValueError:
                flash("Invalid user ID", category="error")
        elif user_id_unblock:
            try:
                user_id = int(user_id_unblock)
                user = User.query.get(user_id)
                if user: 
                    user.status = "valid"
                    db.session.commit()
                else:
                    flash("User not found", category="error")
            except ValueError:
                flash("Invalid user ID", category="error")
        elif user_verify:
            try:
                user_id = int(user_verify)
                user = User.query.get(user_id)
                if user: 
                    user.verified = "yes"
                    db.session.commit()
                else:
                    flash("User not found", category="error")
            except ValueError:
                flash("Invalid user ID", category="error")
        elif user_delete:
            try:
                user_id = int(user_delete)
                user = User.query.get(user_id)
                if user and user_id != 1:

                    for note in user.notes:

                        for image in note.images:
                            db.session.delete(image)
                        for link in note.links:
                            db.session.delete(link)
                        db.session.delete(note)

                    db.session.delete(user)
                    db.session.commit()
                    flash("User and all related data successfully deleted", category="success")
                else:
                    flash("User not found or is an admin", category="error")
            except ValueError:
                flash("Invalid user ID", category="error")  

    users = User.query.all()
    user_count = db.session.query(func.count(User.id)).scalar()
    project_count = db.session.query(func.count(Note.id)).scalar()
    return render_template("admin.html", user=current_user, users=users, user_count=user_count, project_count=project_count)

website/templates/admin.html
{% extends "base.html" %} 

{% block title %}Admin{% endblock %}

{% block content %}
    <style>
        .container_admin {
            min-height: 800px;
            padding: 10px;
        }
        .box {
            width: 100%;
            min-height: 10px;
            padding: 10px;
            margin-top: 5px;
            border: 1px solid #803bff;
            border-radius: 5px;
            display: flex;
            flex-direction: column;
            align-items: top;
            justify-content: space-between;
        }
        .un-block-form{
            display: flex;
            flex-wrap: wrap;
            align-items: center;
            justify-content: center;
        }
        .form-control{
            width: auto;
            margin: 4px;
        }
        button{
            margin-top: 2px;
        }
    </style>

    <div class="container_admin">
        {% if user.email == "fryderyk.otolski@gmail.com" %}
        <h1>Welcome fr3d!</h1>
        <br>
        <p>All users: {{ user_count }}</p>
        <p>All projects: {{ project_count }}</p>
        <br>
        <div class="un-block-form">
            <form method="POST" class="form-control">
                <label for="block">Enter id of user that you want to block</label>
                <input type="text" class="form-control" id="block" name="block" placeholder="Enter id">
                <button type="submit" class="btn-primary">Block</button>
            </form>
            <br>
            <form method="POST" class="form-control">
                <label for="unblock">Enter id of user that you want to unblock</label>
                <input type="text" class="form-control" id="unblock" name="unblock" placeholder="Enter id">
                <button type="submit" class="btn-primary">UnBlock</button>
            </form>
            <form method="POST" class="form-control">
                <label for="verify">Enter id of user that you want to verify</label>
                <input type="text" class="form-control" id="verify" name="verify" placeholder="Enter id">
                <button type="submit" class="btn-primary">Verify</button>
            </form>
            <form method="POST" class="form-control">
                <label for="verify">Enter id of user that you want to delete</label>
                <input type="text" class="form-control" id="delete" name="delete" placeholder="Enter id">
                <button type="submit" class="btn-primary">DELETE</button>
            </form>
        </div>
        <br>

            {% for user in users %}
                <div class="box">
                    <p>{{ user.email }}</p>
                    <p>Id: {{ user.id }}</p>
                    <p>Username: {{ user.first_name }}</p>
                    <p>Surename & name: {{ user.name_surname }}</p>
                    <p>Account created: {{ user.date }}</p>
                    <p>Status: {{ user.status }}</p>
                    <p>Verified: {{ user.verified }}</p>
                    <p>Projects: {{ user.notes|length }}</p>
                </div>
            {% endfor %}
        {% else %}
        <h1>Acces denied!</h1>
        {% endif %}
    </div> 
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Styles -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/home.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/sign_up.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/login.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/facts.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/shop.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/password.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/token.css') }}">

    <link rel="icon" href="static/images/nessdy_favicon.png" type="image/x-icon" />

    <!-- Font font-family: "Playfair Display", serif;-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet">

    <!--font-family: "Montserrat", sans-serif;-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <title>{% block title %}NESSDY.com{% endblock %}</title>
</head>
<body>
  <!-- JavaScript file -->
  <script type="text/javascript" src="{{ url_for('static', filename='toggle.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='flash_close.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='removeProject.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='toggle_desc.js') }}"></script>

  <!-- This block displays flash messages. It uses for loop to go through messages and display them -->
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {%for category, message in messages %}
    {% if category == 'error' %}
    <div class="alert" role="alert">
      {{ message }}
    </div>
    {% else %}
    <div class="alert" role="alert">
        {{ message }}
    </div>
    {% endif %}
    {% endfor %}
  {% endif %}
  {% endwith %}

  <div class="container">
      <!-- Navbar -->
      <nav class="navbar">
        <a href="/">  <img src="{{ url_for('static', filename='images/nessdy_logo2.png') }}">  </a>

        <div class="nav-menu">
            {% if user.is_authenticated %}
            
            <a href="/" class="nav-link nav-item li1">About</a>
            <a href="/cloud" class="nav-link nav-item li2">Cloud</a>
            <a href="/create" class="nav-link nav-item li3">Create</a>
            <a href="/logout" class="nav-link nav-item li4">Logout</a>
            <a href="/settings" class="nav-link nav-item li2">Config</a>

            {% else %}
            
            <a href="/" class="nav-link li1 nav-item">About</a>
            <a href="/cloud" class="nav-link li2 nav-item">Cloud</a>
            <a href="/login" class="nav-link li4 nav-item">Login</a>
            <a href="/sign-up" class="nav-link li2 nav-item">Sign up</a>

            {% endif %}
          </div>
        <div class="hamburger">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </div>
        <p class="space_header" >{{ user.first_name }}</p>
      </nav>
      {% block content %}
      {% endblock %}
      <br>
      <div class="footer">
        <ul>
          <li>
            <img class="logofooter" src="{{ url_for('static', filename='images/nessdy_logo2.png') }}">
          </li>
          <li>
            <p>Where creativity meets opportunity.</p>
            <p>Discover emerging talent, innovative projects,</p>
            <p>and thoughtfully developed ideas.</p>
            <p>Every collaboration is driven by passion,</p>
            <p>designed to inspire, and aimed at growth.</p>
          </li>
          <li>
            <h2>Follow Us</h2> 
            <br>
            <a href="https://www.instagram.com/_nessdy_?igsh=MW9vMGkwdm50OWJwMw%3D%3D&utm_source=qr" target="_blank"><p class="socialm" >Instagram</p></a>
            <a href="https://www.facebook.com/profile.php?id=61575508590029" target="_blank"><p class="socialm" >Facebook</p></a>
          </li>
          <li>
            <h2>Explore</h2>
            <br>
            <p>Innovative projects</p>
            <p>Breathtaking ideas</p>
            <p>Creative community</p>
          </li>
        </ul>
        <br>
        <div class="rights">
          <p> © All rights reserverd nessdy.com</p>
        </div>
      </div>
    </div>
</body>
</html>

website/templates/facts.html
{% extends "base.html" %} 

{% block title %}My Projects{% endblock %}

{% block content %}
<div class="projects_container">
    <h1>CREATE AREA</h1>
    <br>
    <p>Read the instructions carefully</p>
    <br>
    <form method="POST" class="enter_area" enctype="multipart/form-data">
        <p>When you create a project, it’s instantly uploaded to the Nessdy Cloud, where it becomes visible to the entire community.</p>
        <p>You can add social links, photos, a title, description, category, and specific details — everything others need to explore what you’ve made.</p>
        <p>It’s a chance to share your vision, get noticed, and connect with people who appreciate your creativity.</p>
        <p>Whether you're showcasing art, a concept, or something totally unique, your project becomes part of a space built to inspire and empower creators like you.</p>
        <br>
        <h4>Add the title (required)</h4>
        <textarea name="title" id="title" class="form_title" placeholder="Enter a short title (max 50 characters). Do not use special characters"></textarea>
        <p style="color: red;">Required! Do not use special characters</p>
        <br>
        <h4>Add the description (required)</h4>
        <textarea name="note" id="note" class="form" placeholder="Enter details about your project (max 30,000 characters)"></textarea></textarea>
        <p style="color: red;">Required!</p>
        <br>
        <h4>Choose category</h4>
        <div class="custom-select">
            <select name ="select" id="select" class="select">
                <option value="all">Other</option>
                <option value="activism">Activism & Social Impact</option>
                <option value="animation">Animation & Illustration</option>
                <option value="ar-vr">AR/VR</option>
                <option value="community">Community Projects</option>
                <option value="digital-art">Digital Art</option>
                <option value="diy">DIY & Crafts</option>
                <option value="education">Education</option>
                <option value="fashion">Fashion & Textiles</option>
                <option value="film">Film & Video</option>
                <option value="game-dev">Game Development</option>
                <option value="graphic-design">Graphic Design</option>
                <option value="literature">Literature & Writing</option>
                <option value="music">Music & Audio Production</option>
                <option value="painting">Painting</option>
                <option value="photography">Photography</option>
                <option value="product-design">Product Design</option>
                <option value="programming">Programming</option>
                <option value="web-dev">Web Development</option>
            </select>
        </div>
        <p style="color: red;">Required!</p>
        <br>
        <h4>Add the specifications (optional)</h4>
        <textarea name="spec" id="spec" class="form_additional" placeholder="List the items or tools you used (max 500 characters)"></textarea>
        <br>
        <h4>Social media links (optional)</h4>
        <textarea name="social" id="social" class="form_additional" placeholder="Add social media links"></textarea>
        <p style="color: red;">Attention. Harmful links will be removed!</p>
        <br>
        <h4>Add images (optional) max 5 - 25MB</h4>
        <input type="file" name="images" id="images" class="form_additional" accept="image/*" multiple>
        <p style="color: red;">Max 5- 25MB</p>
        <br>
        <div>
            <button type="submit" class="btn">CREATE</button>
        </div>
    </form>
    <br>
    <h1>MY PROJECTS</h1>
    <br>
    <ul class="list-group" id="notes">
        {% for note in user.notes %}
        <h3 class="note-title">{{ note.title }} ~ {{ user.first_name }}</h3>
        <li class="list-group-item">
            <div class="list-group-item-navigation">
                <div class="collapsible" onclick="toggleContent(this)">Show all</div>
                <button type="button" class="close" onclick="deleteNote( {{ note.id }} )">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div> 
            <div class="content">
                <h4 class="space">{{ note.title }} - {{ note.category }}</h4>
                <h4 class="space">Description</h4>
                <p class="description">{{ note.data.replace('\n', '<br>') | safe }}</p>
                <h4 class="space">{% if note.spec and note.spec|trim != '' %} Specifications {% endif %}</h4>
                <p class="description">{{ note.spec }}</p>
                <h4 class="space">{% if note.images and note.images|trim != '' %} Uploaded images {% endif %}</h4>
                <div class="images">
                    {% for image in note.images %}
                        <img src="{{ url_for('static', filename='uploads/' + image.path) }}">
                    {% endfor %}
                </div>
                <h4 class="space">{% if note.links and note.links|trim != '' %} Social media {% endif %}</h4>
                {% for link in note.links %}
                    <div class = "media-link"><a href="{{ link.link }}" target="_blank">{{ link.link }}</a></div>
                    <br>
                {% endfor %}  
            </div>
        </li>
        <p class="date" >{{ note.date }}</p>
        <br>
        {% endfor %}
    </ul>
    <br> 
</div>


{% endblock %}

website/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="slider">
    <div class="slides">
        <div class="slide">
            <img src="static/images/img1.png" alt="img 1">
        </div>
    </div>
</div>
<div class="main-content">
    {% if user.is_authenticated %}
        <!--<h1>Welcome {{ user.first_name }}</h1>-->
    {% else %}
        <!--<h1>Welcome</h1>-->
    {% endif %}
    <div class="nessdy-texts">
        <ul>
            <li>
                <h1>NESSDY is a youthful</h1><h1>Polish initiative</h1>
            </li>
            <li>
                <p>
                    At NESSDY, we celebrate creativity and the joy of sharing. 
                    We're a community where people from all walks of life come together to showcase their unique ideas and projects — simply because they want to.
                </p>
            </li>
            <li>
                <h1>Collaboration with young artists</h1>
                <h1>is our mission</h1>
            </li>
            <li>
                <p>
                    We’re passionate about nurturing creativity and empowering emerging artists. 
                    By collaborating with young creators, we offer a valuable platform for them to share their ideas, bring projects to life, and gain recognition within the creative community.
                </p>
                <br>
                <p>
                    Our mission is to help artists grow, develop their skills, and refine their craft. Every project becomes a stepping stone — a chance to build a portfolio, gain experience, 
                    and connect with a wider audience. We celebrate every unique perspective and work to integrate those voices into our community.
                </p>
            </li>
            <li>
                <h1>Join us and become a creator</h1>
            </li>
            <li>
                <p>
                    We invite everyone to join our community and become a creator!
                    Whether you are an artist, an inventor, or simply someone with a passion for sharing ideas, 
                    you will find a welcoming space here. Dive into a treasure trove of inspiring projects and innovative concepts contributed by people just like you.
                </p>
            </li>
        </ul>
    </div>
   
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="login-holder">
    <form method="POST" class="login-form">
        <h3>Login</h3>
        <div class="form-group">
            <label for="email">Email Adress</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label for="password1">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
        </div>
        <div class="password"> <p>Forgot password? Click - </p> <a href="/reset" type="submit"> here</a> </div>
        <br />
        <button type="submit" class="btn-primary">Login</button>
    </form>
</div>
{% endblock %}

website/templates/password.html
{% extends "base.html" %}

{% block content %}
<div class="login-holder">
    <form method="POST" class="login-form">
        <h3>Reset</h3>
        <div class="form-group">
            <label for="email">Enter Email Adress</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
        </div>
        <p>We will sent you a code</p>
        <p>to reset your password</p>
        <br>
        <button type="submit" class="btn btn-primary">Send</button>
    </form>
</div>
{% endblock %}

website/templates/shop.html
{% extends "base.html" %}

{% block content %}
<div class="projects_container">
    <h1 class="title-text">WELCOME TO NESSDY CLOUD</h1>
    <br>
    <p class="title-text">Here, you will find a list of all the projects that have been created</p>
    <br>
    <ul class="list-group" id="notes">
        <form method="get" action="{{ url_for('views.shop') }}">
            <label for="select">Filter by:</label>
            <select name="category" id="select" class="select" onchange="this.form.submit()">
                <option value="all" {% if selected_category == 'all' %}selected{% endif %}>No filter</option>
                <option value="activism" {% if selected_category == 'activism' %}selected{% endif %}>Activism & Social Impact</option>
                <option value="animation" {% if selected_category == 'animation' %}selected{% endif %}>Animation & Illustration</option>
                <option value="ar-vr" {% if selected_category == 'ar-vr' %}selected{% endif %}>AR/VR</option>
                <option value="community" {% if selected_category == 'community' %}selected{% endif %}>Community Projects</option>
                <option value="digital-art" {% if selected_category == 'digital-art' %}selected{% endif %}>Digital Art</option>
                <option value="diy" {% if selected_category == 'diy' %}selected{% endif %}>DIY & Crafts</option>
                <option value="education" {% if selected_category == 'education' %}selected{% endif %}>Education</option>
                <option value="fashion" {% if selected_category == 'fashion' %}selected{% endif %}>Fashion & Textiles</option>
                <option value="film" {% if selected_category == 'film' %}selected{% endif %}>Film & Video</option>
                <option value="game-dev" {% if selected_category == 'game-dev' %}selected{% endif %}>Game Development</option>
                <option value="graphic-design" {% if selected_category == 'graphic-design' %}selected{% endif %}>Graphic Design</option>
                <option value="literature" {% if selected_category == 'literature' %}selected{% endif %}>Literature & Writing</option>
                <option value="music" {% if selected_category == 'music' %}selected{% endif %}>Music & Audio Production</option>
                <option value="painting" {% if selected_category == 'painting' %}selected{% endif %}>Painting</option>
                <option value="photography" {% if selected_category == 'photography' %}selected{% endif %}>Photography</option>
                <option value="product-design" {% if selected_category == 'product-design' %}selected{% endif %}>Product Design</option>
                <option value="programming" {% if selected_category == 'programming' %}selected{% endif %}>Programming</option>
                <option value="web-dev" {% if selected_category == 'web-dev' %}selected{% endif %}>Web Development</option>
            </select>
        </form>
        <br>
        {% for note in notes %}
        <h3 class="note-title">{{ note.title }} ~ {{ note.username }}</h3>
        <li class="list-group-item">
            <div class="list-group-item-navigation">
                <div class="collapsible" onclick="toggleContent(this)">Show all</div>
                {% if user.email == "fryderyk.otolski@gmail.com" %}
                    <button type="button" class="close" onclick="deleteNote( {{ note.id }} )">
                        <span aria-hidden="true">&times;</span>
                    </button>
                {% endif %}
            </div>
            <div class="content">
                <h4 class="space">{{ note.title }}</h4>
                <h4 class="space">Description</h4>
                <p class="description">{{ note.data.replace('\n', '<br>') | safe }}</p>
                <h4 class="space">{% if note.spec and note.spec|trim != '' %} Specifications {% endif %}</h4>
                <p class="description">{{ note.spec }}</p>
                <h4 class="space">{% if note.images and note.images|trim != '' %} Uploaded images {% endif %}</h4>
                <div class="images">
                    {% for image in note.images %}
                        <img src="{{ url_for('static', filename='uploads/' + image.path) }}">
                    {% endfor %}
                </div>
                <h4 class="space">{% if note.links and note.links|trim != '' %} Social media {% endif %}</h4>
                {% for link in note.links %}
                    <div class = "media-link"><a href="{{ link.link }}" target="_blank">{{ link.link }}</a></div>
                    <br>
                {% endfor %}  
            </div>
        </li>
        <p class="date">{{ note.date.strftime('%Y-%m-%d') }}</p>
        <br>
        {% endfor %}
    </ul>
    <br>
</div>
{% endblock %}